baseURL = "https://csralvall.github.io"
languageCode = "en-us"
title = "csralvall"
theme="archie"

# Code Highlight
pygmentsstyle = "monokai"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

paginate=3 # articles per page

[params]
	mode="toggle" # color-mode → light,dark,toggle or auto
	useCDN=true # don"t use CDNs for fonts and icons, instead serve them locally.
	subtitle = "Documenting myself"
  copyright = "This site is licensed under [CC BY-SA 4.0](https://creativecommons.org/licenses/by-sa/4.0/)."


# Social Tags

[[params.social]]
name = "GitHub"
icon = "github"
url = "https://github.com/csralvall"

# Main menu Items

[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "Posts"
url = "/"
weight = 2

[[menu.main]]
name = "About"
url = "/"
weight = 3
